# -*- coding: utf-8 -*-
"""Python Programming - Lab - 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCHOcw2-LBPZqXIm-6v5q7Z1HrIQZywv

<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Python Programming - 2101CS405</b></center>
<center><b><h1>Lab - 4</b></center>    
<pre>

# String

### 01) WAP to check given string is palindrome or not.
"""

a=input("Enter a String : ")
rev=a[::-1]
if(a==rev):
  print("String is palindrom.")
else:
  print("String is not Palindrom.")

"""### 02) WAP to reverse the words in given string."""

a=input("Enter Sentence : ")
rev=a.split(" ")
for i in rev[::-1]:
  print(i,end=" ")

"""### 03) WAP to remove ith character from given string"""

a=input("Enter a String: ")
b=int(input("Enter a position of Character you want to remove : "))
string=a[:b-1]+a[b:]
string

"""### 04) WAP to find length of String without using len function."""

a=input("Enter a String : ")
count=0
for i in a:
  count+=1
print("Length of string is : ",count)

"""### 05) WAP to print even length word in string."""

a=input("ENter a String : ")
ch=a.split(" ")
print("String : ",ch)
print("Even length Word in String : ")
for i in ch:
  if len(i)%2==0:
    print(i,end=",")

"""### 06) WAP to count numbers of vowels in given string."""

a=input("Enter a String : ")
count=0
for i in a:
  if (i=='a' or i=='e' or i=='i' or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
    count+=1
print("Total vowels in a String = ",count)

"""### 07) WAP to convert given array to string."""

a=['I','AM','Student','Of','Darshan','University']
s=" "
print(s.join(a))

"""### 01) WAP to find out duplicate characters in given string."""

string = input("Enter String : ").lower()
dictionary={}
for i in string:
    if string.count(i) > 1:
        dictionary[i]=string.count(i);
print(dictionary)

"""### 02) WAP to capitalize the first and last character of each word in a string."""

s=input("Enter a String : ")
list=s.split(" ")
st=' '
for i in list:
  st+=i[0].upper()+i[1:len(i)-1]+i[len(i)-1].upper()+" "
print(st)

"""### 03) WAP to find Maximum frequency character in String."""

string = input("Enter String : ").lower()
dictionary={}
for i in string:
    if string.count(i) > 1:
        dictionary[i]=string.count(i);
print(max(dictionary,key=dictionary.get),end=' ')
print("=",dictionary[max(dictionary,key=dictionary.get)])

"""### 04) WAP to find Minimum frequency character in String."""

string = input("Enter String : ").lower()
dictionary={}
for i in string:
    dictionary[i]=string.count(i);
print(min(dictionary,key=dictionary.get),end=' ')
print("=",dictionary[min(dictionary,key=dictionary.get)])

"""### 05) WAP to check if a given string is binary string or not"""

string=input("Enter a String : ")
for i in string:
  if i not in ["0","1"]:
    print("Given String is not a Binary String.")
    break;
else:
    print("Given String is a Binary String.")